bool searchTableRow(int a, int row, int col);
bool searchTableCol(int a, int row, int col);
bool searchTableBlock(int a, int row, int col);
bool searchMarksRow(int a, int row, int col, bool remove = false);
bool searchMarksCol(int a, int row, int col, bool remove = false);
bool searchMarksBlock(int a, int row, int col, bool remove = false);
bool searchRowMinusBlock(int a, int row, int col, bool remove = false);
bool searchColMinusBlock(int a, int row, int col, bool remove = false);
bool searchBlockMinusRow(int a, int row, int col, bool remove = false);
bool searchBlockMinusCol(int a, int row, int col, bool remove = false);
bool searchMarks(int a, int row, int col);